### ISSUE TITLE
-13- Finish ActionsTab

### ISSUE THREAD

**Issue by elShailee** [elShailee/The-Act-of-Time#12]
# Finish ActionsTab
### Description
`ActionsTab` is partly finished, the following still needs to happen:
 - [x] Implement Timer functionality
   - [x] Convert Unix Time to actual time
   - [x] Make the time tick backwards
   - [x] Create an empty trigger for when an action is finished (will be used to update server later)
 - [x] Create an 'Open Actions Window' button, and have it open an empty window.
 - [x] Touch-up the CSS a bit to make it look decent.

### Specifications
 - You can get a visual idea at `Actions Window.drawio` at the Layouts folder in Google Drive.
 - This is a partly done work, if anything does't make sense ask @elShailee.
 - In general, feel free to ask a ton of questions!

Good luck!
Shailee

**Comment by shemeshx** [comment]
> # Finish ActionsTab
> ### Description
> `ActionsTab` is partly finished, the following still needs to happen:
> 
> * [ ]  Implement Timer functionality
>   
>   * [x]  Convert Unix Time to actual time
>   * [ ]  Make the time tick backwards
>   * [ ]  Create an empty trigger for when an action is finished (will be used to update server later)
> * [ ]  Create an 'Open Actions Window' button, and have it open an empty window.
> * [ ]  Touch-up the CSS a bit to make it look decent.
> 
> ### Specifications
> * You can get a visual idea at `Actions Window.drawio` at the Layouts folder in Google Drive.
> * This is a partly done work, if anything does't make sense ask @elShailee.
> * In general, feel free to ask a ton of questions!
> 
> Good luck!
> Shailee

just need to improve some CSS.

**Comment by shemeshx** [comment]
finish styling the button but didn't implement the dialog. will be implemented when i will finish with Redux.
